server { 
  listen 80; 
  root /app/web; 

  index index.php index.html; 

  location / {
    try_files $uri $uri/ /index.php$is_args$args;
  }

  location ~ \.php$ { 
    fastcgi_intercept_errors on;
    fastcgi_pass unix:/run/php/php8.2-fpm.sock;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $realpath_root/index.php;
    fastcgi_param SERVER_NAME $host;
  }

  location /templates/ {
    internal;
  }
}